\*********KEYPAD*********
\COLUMNS
10 CONSTANT C1
16 CONSTANT C2
1B CONSTANT C3
A CONSTANT C4
\ROWS
12 CONSTANT R1
17 CONSTANT R2
18 CONSTANT R3
19 CONSTANT R4

VARIABLE PASSWORD_FLAG
VARIABLE KEY_COUNTER
VARIABLE KEY_TEMP

: PRESSED ( pin -- flag )
    PIN_LEVEL 1 = ;
: CHECK_EMIT ( -- flag )
    PASSWORD_FLAG @
    IF 2A 1 SEND_COMMAND ELSE DUP 1 SEND_COMMAND THEN ;
: KEYPAD_FALLING ( register -- )
    BEGIN DUP EVENT_DETECT UNTIL 1F4 MSEC_TIMES CLEAR_EVENT ;
: ROW_PRESSED ( cod_ascii, row -- )
    DUP PRESSED IF KEYPAD_FALLING KEY_COUNTER INCREMENT CHECK_EMIT
    ELSE 2DROP THEN ;

: ROWS_CHECK ( v1 v2 v3 v4 -- value )
    >R >R >R >R
    R> R1 ROW_PRESSED R> R2 ROW_PRESSED 
    R> R3 ROW_PRESSED R> R4 ROW_PRESSED ;

: COLS_CHECK ( -- values )
  C1 GPON
  31 34 37 2A ROWS_CHECK
  C1 GPOFF
  C2 GPON
  32 35 38 30 ROWS_CHECK
  C2 GPOFF
  C3 GPON
  33 36 39 23 ROWS_CHECK
  C3 GPOFF 
  C4 GPON
  41 42 43 44 ROWS_CHECK
  C4 GPOFF ;

: ROW_FALLING ( -- )
    R1 FALLING_EDGE_DETECT_ENABLE
    R2 FALLING_EDGE_DETECT_ENABLE
    R3 FALLING_EDGE_DETECT_ENABLE
    R4 FALLING_EDGE_DETECT_ENABLE ;

: KEYPAD_INIT ( -- )
    ROW_FALLING
    12 GPFSEL GPIO_INPUT \row1 Port GPIO18
    17 GPFSEL GPIO_INPUT \row2 Port GPIO23
    18 GPFSEL GPIO_INPUT \row3 Port GPIO24
    19 GPFSEL GPIO_INPUT \row4 Port GPIO25
    10 GPFSEL GPIO_OUTPUT \Col Port GPIO16
    16 GPFSEL GPIO_OUTPUT \Col Port GPIO22
    1B GPFSEL GPIO_OUTPUT \Col Port GPIO27
    A GPFSEL GPIO_OUTPUT \Col Port GPIO10
    C1 GPOFF
    C2 GPOFF
    C3 GPOFF
    C4 GPOFF ;

: READ_VALUES ( value flag -- )
    PASSWORD_FLAG ! 1 KEY_COUNTER !
    KEY_TEMP ! BEGIN
    COLS_CHECK KEY_TEMP @ KEY_COUNTER @ <
    UNTIL ;
