\*********LCD*********
27 CONSTANT LCD_SLAVET \PCF8574T
C CONSTANT CMD_HIGH
8 CONSTANT CMD_LOW
VARIABLE LCD_COUNTER
VARIABLE LCD_TEMP

: SEND ( -- ) LCD_SLAVET 1 WRITE_I2C ;
: SEND_VALUE ( -- ) OR 200 USEC_TIMES SEND ;
: SEND_PREPARE ( cod_Ascii -- data[3-0] data[7-4] )
    DUP 10 / 10 * SWAP OVER - 10 * SWAP ;
: SEND_COMMAND ( cod_Ascii boolean -- )
    >R SEND_PREPARE
    DUP CMD_HIGH RSP@ @ + SEND_VALUE CMD_LOW RSP@ @ + SEND_VALUE
    DUP CMD_HIGH RSP@ @ + SEND_VALUE CMD_LOW RSP@ @ + SEND_VALUE R> DROP ;
: SEND_STRING ( addr len -- )
    0 LCD_COUNTER !
    LCD_TEMP !
    >R BEGIN
    RSP@ @ LCD_COUNTER @ + C@ 1 SEND_COMMAND LCD_COUNTER INCREMENT_RETURN LCD_TEMP @ =
    UNTIL R> DROP ;

\ COMMANDS SET
: FUNCTION_SET ( -- ) 2C SEND 200 USEC_TIMES 28 SEND ;
: DISPLAY_ON ( -- ) F 0 SEND_COMMAND ;
: CLEAR_DISPLAY ( -- ) 1 0 SEND_COMMAND ;
: DISPLAY_SHIFT ( -- ) 1F 0 SEND_COMMAND ;
: ENTRY_MODE ( -- ) 6 0 SEND_COMMAND ;
: DISPLAY_R2 ( -- ) C0 0 SEND_COMMAND ;
: DISPLAY_R1 ( -- ) 80 0 SEND_COMMAND ;

\ Display initializzation
: INIT_LCD ( -- )
    FUNCTION_SET \ send 2C 28 FUNCTION_SET[4bit,2lines,5x8dots]
    DISPLAY_ON \ send C 8 FC F8 DIPLAYON CURSORON BLINKINGON
    ENTRY_MODE ;
