VARIABLE LOG_COUNTER
VARIABLE CRCBUFFER
A CONSTANT MAXLOGUSERS
CREATE USERLOG MAXLOGUSERS CELLS ALLOT
CREATE USERLOGTIME MAXLOGUSERS CELLS ALLOT
CREATE FLAG MAXLOGUSERS CELLS ALLOT 

: USERLOG_INIT ( -- ) 0 CRCBUFFER ! ;

: CREATE_STRING ( usercode flag -- addr len ) 
    DUP 0 = IF S" USER ___ LOGGED SUCCESSFULLY " ELSE
    DUP 1 = IF S" USER ___ PASSWORD WRONG! " THEN THEN
    ROT DROP SWAP >R SWAP
    DUP 100 / DUP 100 * ROT SWAP - DUP 10 / DUP 10 * ROT SWAP -
    30 + RSP@ @  7 + C! 30 + RSP@ @  6 + C! 30 + RSP@ @  5 + C!
    R> SWAP ;

: REGISTER_LOG ( usercode addr_time flag -- ) 
    FLAG CRCBUFFER @ MAXLOGUSERS MOD CELLS + !
    USERLOGTIME CRCBUFFER @ MAXLOGUSERS MOD CELLS + !
    USERLOG CRCBUFFER @ MAXLOGUSERS MOD CELLS + !
    CRCBUFFER INCREMENT ;

: PRINT_LOG ( usercode -- ) 
    0 LOG_COUNTER ! >R
    BEGIN
        USERLOG LOG_COUNTER @ CELLS + @ DUP RSP@ @ =
        IF FLAG LOG_COUNTER @ CELLS + @ CREATE_STRING PRINT_HDMI
        USERLOGTIME LOG_COUNTER @ CELLS + @ 10 PRINT_HDMI HDMI_RETURN
        ELSE DROP THEN
        LOG_COUNTER INCREMENT_RETURN MAXLOGUSERS =
    UNTIL R> DROP ;
